version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9000:3000'
      - '9229:9229'
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - './data:/usr/src/app/data'